// Package media stores, validates and serves uploaded assets (web-v1.md §12, §12.1).
package media

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"syscall"
	"time"
)

// Storage abstracts where asset bytes live. Keys are opaque and generated by the server; callers
// never pass user input as a key. Only the local backend exists; S3 would implement the same
// interface without changing /media/{id} URLs (web-v1.md §12).
type Storage interface {
	Name() string
	// Put stores size bytes from r under key. The object must not exist.
	Put(ctx context.Context, key string, r io.Reader, size int64) error
	// Open returns a seekable reader so HTTP range requests never load the object into memory.
	Open(ctx context.Context, key string) (Object, error)
	Stat(ctx context.Context, key string) (Info, error)
	Delete(ctx context.Context, key string) error
}

type Info struct {
	Size    int64
	ModTime time.Time
}

type Object interface {
	io.ReadSeekCloser
	Info() Info
}

var ErrNotFound = errors.New("object not found")

var keyPattern = regexp.MustCompile(`^[0-9a-f]{2}/[0-9a-f]{2}/[0-9a-f]{32}$`)

// NewKey returns an opaque, sharded key such as "3f/a1/3fa1…" (32 random hex characters).
func NewKey() string {
	b := make([]byte, 16)
	_, _ = rand.Read(b)
	h := hex.EncodeToString(b)
	return h[:2] + "/" + h[2:4] + "/" + h
}

// Local keeps objects under root/objects and staging files under root/tmp (same filesystem, so
// the final write is an atomic rename). The directory is never exposed as static files.
type Local struct{ root string }

func NewLocal(root string) (*Local, error) {
	for _, dir := range []string{"objects", "tmp"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o750); err != nil {
			return nil, fmt.Errorf("prepare media storage: %w", err)
		}
	}
	return &Local{root: root}, nil
}

func (l *Local) Name() string { return "local" }

// TempDir is where uploads are staged before validation.
func (l *Local) TempDir() string { return filepath.Join(l.root, "tmp") }

func (l *Local) path(key string) (string, error) {
	if !keyPattern.MatchString(key) {
		return "", fmt.Errorf("invalid object key")
	}
	return filepath.Join(l.root, "objects", filepath.FromSlash(key)), nil
}

func (l *Local) Put(ctx context.Context, key string, r io.Reader, size int64) error {
	dst, err := l.path(key)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o750); err != nil {
		return err
	}
	// Fast path: a staged file on the same filesystem is moved into place atomically.
	if f, ok := r.(*os.File); ok && strings.HasPrefix(f.Name(), l.TempDir()+string(os.PathSeparator)) {
		if _, err := os.Stat(dst); err == nil {
			return fmt.Errorf("object already exists")
		}
		return os.Rename(f.Name(), dst)
	}
	tmp, err := os.CreateTemp(l.TempDir(), "put-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	n, err := io.Copy(tmp, r)
	if err == nil && n != size {
		err = fmt.Errorf("short write: %d of %d bytes", n, size)
	}
	if err == nil {
		err = tmp.Sync()
	}
	if cerr := tmp.Close(); err == nil {
		err = cerr
	}
	if err != nil {
		return err
	}
	return os.Rename(tmp.Name(), dst)
}

type localObject struct {
	*os.File
	info Info
}

func (o localObject) Info() Info { return o.info }

func (l *Local) Open(_ context.Context, key string) (Object, error) {
	p, err := l.path(key)
	if err != nil {
		return nil, err
	}
	f, err := os.Open(p)
	if errors.Is(err, os.ErrNotExist) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	st, err := f.Stat()
	if err != nil {
		f.Close()
		return nil, err
	}
	return localObject{File: f, info: Info{Size: st.Size(), ModTime: st.ModTime()}}, nil
}

func (l *Local) Stat(_ context.Context, key string) (Info, error) {
	p, err := l.path(key)
	if err != nil {
		return Info{}, err
	}
	st, err := os.Stat(p)
	if errors.Is(err, os.ErrNotExist) {
		return Info{}, ErrNotFound
	}
	if err != nil {
		return Info{}, err
	}
	return Info{Size: st.Size(), ModTime: st.ModTime()}, nil
}

func (l *Local) Delete(_ context.Context, key string) error {
	p, err := l.path(key)
	if err != nil {
		return err
	}
	if err := os.Remove(p); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

// FreeBytes reports the space available to unprivileged writers on the volume.
func (l *Local) FreeBytes() (uint64, error) {
	var st syscall.Statfs_t
	if err := syscall.Statfs(l.root, &st); err != nil {
		return 0, err
	}
	return uint64(st.Bavail) * uint64(st.Bsize), nil //nolint:unconvert // field types differ per OS
}

// isNoSpace reports disk-full errors so they surface as 507 instead of a generic failure.
func isNoSpace(err error) bool {
	return errors.Is(err, syscall.ENOSPC) || errors.Is(err, syscall.EDQUOT)
}
