-- Contact form: messages, durable send jobs, sanitized attempts and rate limits (web-v1.md §13.1).

-- +goose Up
-- Server-side secrets generated by the API itself (e.g. the HMAC key for rate-limit buckets).
CREATE TABLE app_secrets (
    name       text        PRIMARY KEY,
    value      bytea       NOT NULL CHECK (length(value) >= 32),
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Personal data lives only here and in the frozen job payload; both are purged after retention.
CREATE TABLE contact_messages (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    locale       text        NOT NULL CHECK (locale IN ('es', 'en')),
    name         text        NOT NULL,
    email        text        NOT NULL,
    message      text        NOT NULL,
    client_key   text        NOT NULL UNIQUE,
    payload_hash bytea       NOT NULL,
    received_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX contact_messages_received_idx ON contact_messages (received_at DESC);

CREATE TABLE contact_jobs (
    message_id        uuid        PRIMARY KEY REFERENCES contact_messages (id) ON DELETE CASCADE,
    status            text        NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending', 'processing', 'retry_wait', 'accepted_by_provider', 'failed', 'unknown')),
    version           integer     NOT NULL DEFAULT 0,
    payload           jsonb       NOT NULL,
    template_version  integer     NOT NULL,
    idempotency_key   text        NOT NULL,
    attempts          integer     NOT NULL DEFAULT 0,
    max_attempts      integer     NOT NULL CHECK (max_attempts >= 1),
    next_attempt_at   timestamptz NOT NULL,
    -- First attempt that may have reached the provider with the current key (idempotency window).
    first_attempt_at  timestamptz,
    -- An attempt with the current key ended without knowing whether the provider accepted it.
    uncertain         boolean     NOT NULL DEFAULT false,
    lease_token       uuid,
    lease_until       timestamptz,
    provider_email_id text,
    last_error        text,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    finished_at       timestamptz,
    CONSTRAINT contact_jobs_lease CHECK ((status = 'processing') = (lease_token IS NOT NULL AND lease_until IS NOT NULL)),
    CONSTRAINT contact_jobs_accepted CHECK (status <> 'accepted_by_provider' OR provider_email_id IS NOT NULL)
);
CREATE INDEX contact_jobs_due_idx ON contact_jobs (next_attempt_at) WHERE status IN ('pending', 'retry_wait');
CREATE INDEX contact_jobs_lease_idx ON contact_jobs (lease_until) WHERE status = 'processing';

-- Sanitized: outcome, HTTP status, provider error name and request id. Never bodies or PII.
CREATE TABLE contact_attempts (
    message_id          uuid        NOT NULL REFERENCES contact_jobs (message_id) ON DELETE CASCADE,
    attempt             integer     NOT NULL,
    at                  timestamptz NOT NULL,
    idempotency_key     text        NOT NULL,
    outcome             text        NOT NULL CHECK (outcome IN ('accepted', 'transient', 'uncertain', 'permanent', 'lease_expired')),
    http_status         integer,
    error_name          text,
    provider_request_id text,
    PRIMARY KEY (message_id, attempt)
);

-- Rate-limit counters by HMAC bucket (per client or global) and fixed window. Purged after 24 h.
CREATE TABLE contact_rate (
    bucket       text        NOT NULL,
    window_start timestamptz NOT NULL,
    count        integer     NOT NULL,
    PRIMARY KEY (bucket, window_start)
);

-- +goose Down
DROP TABLE contact_rate;
DROP TABLE contact_attempts;
DROP TABLE contact_jobs;
DROP TABLE contact_messages;
DROP TABLE app_secrets;
